name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK to GitHub Release
        if: success()  # Only proceed if the build is successful
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}  # You can change this to use a version number from your Gradle file
          release_name: "Release v${{ github.run_number }}"
          body: "Release description for v${{ github.run_number }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Upload APK asset to Release
        if: success()  # Only upload if the release was created successfully
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/release/*.apk
          asset_name: "uuMusic-release-${{ github.run_number }}.apk"  # You can modify the name as needed
          asset_content_type: application/vnd.android.package-archive
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
#
#  release:
#    needs: build
#    runs-on: ubuntu-latest
#    if: github.event_name == 'push'
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Download Release APK
#        uses: actions/download-artifact@v4
#        with:
#          name: app-release
#          path: app/release/
#
#      - name: Create GitHub Release
#        uses: softprops/action-gh-release@v4
#        with:
#          files: app/release/app-release.apk
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
