name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/release/app-release.apk

#  release:
#    needs: build
#    runs-on: ubuntu-latest
#    if: github.event_name == 'push'
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Download Release APK
#        uses: actions/download-artifact@v4
#        with:
#          name: app-release
#          path: app/release/
#
#      - name: Create GitHub Release
#        uses: softprops/action-gh-release@v4
#        with:
#          files: app/release/app-release.apk
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
